payload:
  - DOMAIN-KEYWORD,bytednsdoc
  - DOMAIN-KEYWORD,peterchen97
  - DOMAIN-SUFFIX,xhscdn.com
  - DOMAIN-KEYWORD,xiaohongshu
  - DOMAIN-SUFFIX,douyinvod.com
  - DOMAIN-SUFFIX,douyinpic.com
  - DOMAIN-KEYWORD,byteimg
  - DOMAIN-KEYWORD,bytedance
  - DOMAIN-SUFFIX,pstatp.com
  - DOMAIN-KEYWORD,kuaishou
  - DOMAIN-SUFFIX,ksyun.com
